### ISSUE TITLE
@Push moves cursos allways to the beginning of text

### ISSUE THREAD

**Issue by sergioszy** [OpenESignForms/vaadin-ckeditor#48] opened 2015-09-15 00:27 UTC
I can't implement CKeditor if Push is enabled, because every 'N' seconds, every Push message, the cursor goes to the beginning of text.

**Comment by OpenESignForms** [comment] 2015-09-15 21:24
We just don't see what you see here.  How are you setting up your editor?  Maybe it's different as we have PUSH enabled (though we don't push anything special yet), but we can access other fields/buttons and interact with the Vaadin app without the editor scrolling or the cursor moving.  

We have code like:
```
CKEditorConfig config = new CKEditorConfig();
config.setupForOpenESignForms(...various params...);
config.setStartupFocus(true);
CKEditorTextField editor = new CKEditorTextField(config);
editor.setCaption(vaadinUi.getMsg("LibDocumentVersionPageForm.editor.label"));
editor.setImmediate(true);
editor.setSizeFull();
editor.setReadOnly(false);
```

And the 'config.setupForOpenESignForms()' basically does these for us:

	public void setupForOpenESignForms(String contextPath, String ckeditorContextIdInSession, String bodyCssClass, String... extraCssFiles) {
		addCustomToolbarLine("{ items: ['Styles','Format','Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat'] }," +
							 "{ items: ['TextColor','BGColor'] }," +
	                         "{ items: ['Font','FontSize'] }," +
	             			 "{ items: ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'] }"); // all wrong icons
		addCustomToolbarLine("{ items: ['Cut','Copy','Paste','PasteText','PasteFromWord'] }," + // paste word wrong
				 			 "{ items: ['Find','Replace'] }," + 
				 			 "{ items: ['Undo','Redo'] }," +
				 			 "{ items: ['NumberedList','BulletedList'] }," + 
				 			 "{ items: ['Outdent','Indent','CreateDiv'] }," + 
				 			 "{ items: ['Table','HorizontalRule','PageBreak','SpecialChar'] }," +
				 			 "{ items: ['Image','Link','Unlink'] }," +
				 			 "{ items: ['Source','ShowBlocks'] }");

		setHeight("300px");
		setBaseFloatZIndex(20000);
		setTabSpaces(4);
		
		disableSpellChecker();
		setDisableNativeSpellChecker(false);
		disableResizeEditor();
		setPasteFromWordNumberedHeadingToList(true);
		//setPasteFromWordRemoveFontStyles(false); -- sadly, we want font color to be kept, but having this creates too much HTML mess
		setPasteFromWordRemoveStyles(false);
		setPasteFromWordPromptCleanup(true);
		
		useCompactTags();
		addWriterRules("script", "{indent : false, breakBeforeOpen : true, breakAfterOpen : true, breakBeforeClose : true, breakAfterClose : true}" );
		addWriterRules("style",  "{indent : false, breakBeforeOpen : true, breakAfterOpen : true, breakBeforeClose : true, breakAfterClose : true}" );
		setWriterIndentationChars("    ");
		
		enableCtrlSWithVaadinSavePlugin();

		addFontName("Calibri/Calibri, Arial, Helvetica, sans-serif");
		
		setStylesSet("esfStyleSet:" + contextPath + "/static/esf/esfStyleSet.js");
		if ( extraCssFiles == null )
			setContentsCss(contextPath + "/static/esf/esf.css");
		else
		{
			String[] cssFiles = new String[extraCssFiles.length+1];
			cssFiles[0] = contextPath + "/static/esf/esf.css";
			for(int i=0; i < extraCssFiles.length; ++i )
				cssFiles[i+1] = contextPath + extraCssFiles[i];
			setContentsCss(cssFiles);
		}
		if ( bodyCssClass == null || "".equals(bodyCssClass) )
			bodyCssClass = "esf";
		else
			bodyCssClass = "esf " + bodyCssClass;
		setBodyClass(bodyCssClass);
		setFilebrowserBrowseUrl(contextPath + "/ckeditorFileBrowser.jsp?ccid="+ckeditorContextIdInSession);
		setFilebrowserWindowWidth("500"); // 4/27/2012 believe there's a bug for any value less than 640 being ignored
		setFilebrowserWindowHeight("500");
		setFilebrowserImageBrowseUrl(contextPath + "/ckeditorImageBrowser.jsp?ccid="+ckeditorContextIdInSession);
		setFilebrowserImageWindowWidth("600");
		setFilebrowserImageWindowHeight("500");
		setAllowedContentAll(); // turn off ACF introduced in CKEditor 4.1 since people can enter whatever they want via the editor SOURCE mode.
		addProtectedSource("/<%.*%>/g"); // allow JSP code like <%=(new java.util.Date())%> or <% any java code you want %>
		addProtectedSource("/<[a-z]*:.*\\/>/g"); // allow JSP tags like <esf:out value="Test"/>

**Comment by sergioszy** [comment] 2015-09-15 22:46
Ok, but...  set you 'setPollInterval(N millisecons);' ?.

If you not set 'setPollInterval()' then works ok.

Thanks in advance!

Best regards!

**Comment by OpenESignForms** [comment] 2015-09-16 21:49
We don't use polling, per se, but if you can debug and find out what is wrong when you turn on polling and perhaps offer a workaround, we can then add some code to do alternate behavior when polling is enabled.  It sounds like the server is telling the client to "setHTML" into the editor so the contents are overwritten with the new values and that likely resets any insertion point/cursor.  But it's not clear why the server sets the field's value other than initially as it normally only gets changes from the client.

**Comment by sergioszy** [comment] 2015-09-16 22:29
The value in the editor is not changing, only the cursor position is set to the beginning. About debug, I don't know how to debug and discover what is happen; but I can see that the cursor change the position when the client receives a message from server.

**Comment by juliengresse** [comment] 2015-11-19 13:22
Hi,
SergioSzy is rigth: we've got same issue here. Very annoying when you want to use Vaadin polling in your application.

How can we help to find the bug ?

Do you know if there is a way to enable polling only in certain views ?

**Comment by trajala** [comment] 2016-03-15 12:19
We are also experiencing this issue with our application. Vaadin polling resets the cursor position. I mentioned this issue in easyuploads add-on's Vaadin forum page and @mstahv from Vaadin said that he might have some time to look into this.

**Comment by mstahv** [comment] 2016-03-25 09:38
Tinymcewrapper seems to have exactly the same issue :-(

https://github.com/mstahv/tinymcewrapper/issues/1

It might be easier simply by not to extending Vaadin TextField, but I have a bit hacky workaround to tinymce in works. I can then try to look into ckeditor, unless @OpenESignForms wants to look into this based on my hack.

**Comment by mstahv** [comment] 2016-03-25 09:53
Here is the workaround I did for tinymcewrapper:

https://github.com/mstahv/tinymcewrapper/commit/3fc2f44df2158a6132ca920ca1e0d6808469e79b

**Comment by mstahv** [comment] 2016-03-25 14:30
Pull request #52 should be a fairly safe fix for this issue. This can be tested with the widget project by setting setPollingInterva(3000) and then typing rather fast for couple fo seconds.

**Comment by OpenESignForms** [comment] 2016-03-29 19:44
We will bring in Matti's patch and update our version of Vaadin and CKEditor and give it a test.  We won't be testing the polling issue directly, but if it doesn't break things for us, we'll include it and hopefully it will resolve the issue for those using polling.

**Comment by mstahv** [comment] 2016-03-29 20:28
If you want, it is pretty easty to test with the app you have in the add-on project.Just add this line the beginning of the init method:

		setPollInterval(4000);

Then type in pretty fast into the editor.

Let me know if my fix causes some issue!

**Comment by OpenESignForms** [comment] 2016-03-29 22:48
The 7.10.7 release is uploaded in the vaadin directory.  Please give it a test for the long polling issue and report back if the patch isn't working.

**Comment by mstahv** [comment] 2016-03-30 10:32
Works for me at least!

**Comment by trajala** [comment] 2016-03-31 12:11
Thanks guys for the fix and update! It works in our application as well.

**Closed** 2016-04-01 20:55 UTC
Labels: bug

**Comment by daulet2030** [comment] 2018-04-27 06:07
Hi there, I have this issue again after 7.11.2 upto 7.12.5
I tested from version 7.10.8 upto 7.11.1 the issue is fixed.

**Comment by daulet2030** [comment] 2018-06-13 04:34
@OpenESignForms not going to fix? just making sure...

**Comment by OpenESignForms** [comment] 2018-06-13 14:37
If you have a patch that fixes your issue, we'll try, as we did previously.  But no, we're not likely to work hard trying to figure out what happens in your use case that never happens to us.  So if you can spend your time and figure out what is wrong, like the prior comment about polling intervals, we'd be happy to help out with this open source project.  If you plan to do that, you can open a new case and provide the information.

**Comment by daulet2030** [comment] 2018-06-18 03:46
Sorry, I didnt want to imply anything. I fixed my problem by disabling binder and fetching value with getValue method instead
